"""Scrum of Scrums v2 — Digest Builder

Renders three artifacts from _milestone_health.json:
  1. scrum_digest.md           — full report (what Waki/Katherine see)
  2. scrum_digest_slack.txt    — ready-to-paste Slack mrkdwn (per-TSA thread)
  3. scrum_digest_preview.html — one-screen HTML preview (shareable link)

Usage:
    python kpi/milestone_health_engine.py   # refresh health
    python kpi/scrum_digest_builder.py      # render
"""
import sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
import os, json, html
from collections import defaultdict
from datetime import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT = os.path.join(SCRIPT_DIR, '_milestone_health.json')
OUT_MD = os.path.join(SCRIPT_DIR, 'scrum_digest.md')
OUT_SLACK = os.path.join(SCRIPT_DIR, 'scrum_digest_slack.txt')
OUT_HTML = os.path.join(SCRIPT_DIR, 'scrum_digest_preview.html')

EMOJI = {'red': ':red_circle:', 'yellow': ':large_yellow_circle:',
         'green': ':large_green_circle:', 'done': ':white_check_mark:'}
EMOJI_TXT = {'red': '🔴', 'yellow': '🟡', 'green': '🟢', 'done': '✅'}
STATUS_LABEL = {'red': 'At Risk', 'yellow': 'Watch', 'green': 'On Track', 'done': 'Shipped'}


def short_name(full):
    """'Carlos Guilherme Matos de Almeida da Silva' -> 'Carlos'"""
    if not full:
        return ''
    return full.split()[0]


def linear_view_url(tsa_name, project, milestone=None):
    """Deep-link into Linear filtered view.
    NOTE: Linear doesn't support arbitrary search URLs — we produce the project URL
    when possible, else a textual reference."""
    # fallback: textual
    return None


def slack_card(bucket):
    """Slack mrkdwn card for one milestone/project bucket."""
    m = bucket['metrics']
    status = bucket['status']
    label = STATUS_LABEL[status]
    emoji = EMOJI[status]
    header = bucket['project']
    if bucket['milestone']:
        header += f" — {bucket['milestone']}"

    lines = [f"*{emoji} {header}*  (`{label}`)"]

    # Metrics line
    metric_parts = [f"{m['open']} open / {m['total']} total"]
    if m['overdue']:
        metric_parts.append(f"{m['overdue']} overdue")
    if m['soon'] and status != 'red':
        metric_parts.append(f"{m['soon']} due ≤3d")
    if m['earliest_due']:
        metric_parts.append(f"next due {m['earliest_due']}")
    lines.append("   " + "  ·  ".join(metric_parts))

    # Impact
    lines.append(f"   *Why it matters:* {bucket['impact']}")

    # Reasons (only if not green)
    if status != 'green' and bucket['reasons']:
        lines.append(f"   *Signal:* {'; '.join(bucket['reasons'])}")

    # Top 2 tickets that drive status (overdue first, then soon)
    refs = []
    for issue in bucket.get('open_issues', []):
        if not issue.get('dueDate'):
            continue
        refs.append((issue['dueDate'], issue))
    refs.sort(key=lambda x: x[0])
    if refs:
        for _, issue in refs[:2]:
            lines.append(f"   └─ <{issue['url']}|{issue['id']}> "
                         f"[{issue['status']}] {issue['title'][:80]}  `due {issue['dueDate']}`")
    else:
        lines.append(f"   └─ <https://linear.app/testbox|view in Linear>")

    return "\n".join(lines)


def render_slack(health):
    out = []
    # by TSA
    by_tsa = defaultdict(list)
    for b in health['buckets']:
        by_tsa[b['tsa_name']].append(b)

    out.append(f"*📊 Scrum of Scrums — Milestone Health Digest*")
    out.append(f"_{health['date']} · source of truth: Linear · full details in each ticket_\n")

    # Top summary
    by_status = health['by_status']
    out.append(f"*Team rollup:*  "
               f"🔴 {by_status.get('red', 0)} at risk  ·  "
               f"🟡 {by_status.get('yellow', 0)} watch  ·  "
               f"🟢 {by_status.get('green', 0)} on track  ·  "
               f"✅ {by_status.get('done', 0)} shipped (last 14d)\n")

    for tsa in sorted(by_tsa.keys()):
        cards = by_tsa[tsa]
        # Ignore TSAs who only have "done" or zero
        active = [c for c in cards if c['status'] != 'done']
        if not cards:
            continue
        # header
        reds = sum(1 for c in cards if c['status'] == 'red')
        yellows = sum(1 for c in cards if c['status'] == 'yellow')
        summary_parts = []
        if reds: summary_parts.append(f"🔴 {reds}")
        if yellows: summary_parts.append(f"🟡 {yellows}")
        greens = sum(1 for c in cards if c['status'] == 'green')
        if greens: summary_parts.append(f"🟢 {greens}")
        dones = sum(1 for c in cards if c['status'] == 'done')
        if dones: summary_parts.append(f"✅ {dones}")
        out.append(f"*👤 {short_name(tsa)}*  ·  " + "  ".join(summary_parts))

        for c in cards:
            out.append(slack_card(c))
            out.append("")

    out.append("_Generated by TSA_CORTEX `scrum_digest_builder.py`_")
    return "\n".join(out)


def render_markdown(health):
    out = []
    out.append(f"# Scrum of Scrums — Milestone Health Digest")
    out.append(f"_{health['date']}_  ·  source of truth: Linear\n")
    out.append(f"**Team rollup:** "
               f"{EMOJI_TXT['red']} {health['by_status'].get('red', 0)} at risk · "
               f"{EMOJI_TXT['yellow']} {health['by_status'].get('yellow', 0)} watch · "
               f"{EMOJI_TXT['green']} {health['by_status'].get('green', 0)} on track · "
               f"{EMOJI_TXT['done']} {health['by_status'].get('done', 0)} shipped (14d)\n")

    by_tsa = defaultdict(list)
    for b in health['buckets']:
        by_tsa[b['tsa_name']].append(b)

    for tsa in sorted(by_tsa.keys()):
        out.append(f"## {short_name(tsa)}\n")
        for c in by_tsa[tsa]:
            m = c['metrics']
            emoji = EMOJI_TXT[c['status']]
            header = c['project'] + (f" — {c['milestone']}" if c['milestone'] else "")
            out.append(f"### {emoji} {header}  _({STATUS_LABEL[c['status']]})_")
            metric_parts = [f"{m['open']} open / {m['total']} total"]
            if m['overdue']:
                metric_parts.append(f"**{m['overdue']} overdue**")
            if m['soon'] and c['status'] != 'red':
                metric_parts.append(f"{m['soon']} due ≤3d")
            if m['earliest_due']:
                metric_parts.append(f"next due `{m['earliest_due']}`")
            out.append("  ·  ".join(metric_parts))
            out.append(f"\n**Why it matters:** {c['impact']}")
            if c['status'] != 'green' and c['reasons']:
                out.append(f"\n**Signal:** {'; '.join(c['reasons'])}")

            # top tickets
            refs = [i for i in c.get('open_issues', []) if i.get('dueDate')]
            refs.sort(key=lambda x: x['dueDate'] or '9999-99-99')
            if refs:
                out.append("")
                for issue in refs[:3]:
                    out.append(f"- [{issue['id']}]({issue['url']}) "
                               f"`{issue['status']}` — {issue['title'][:90]} "
                               f"_(due {issue['dueDate']})_")
            out.append("")
    out.append("---")
    out.append("_Generated by TSA_CORTEX — replaces manual daily agenda posts._")
    return "\n".join(out)


def render_html(health):
    status_colors = {
        'red': '#ef4444', 'yellow': '#f59e0b',
        'green': '#10b981', 'done': '#6366f1',
    }

    by_tsa = defaultdict(list)
    for b in health['buckets']:
        by_tsa[b['tsa_name']].append(b)

    h = []
    h.append("<!DOCTYPE html><html><head><meta charset='utf-8'>")
    h.append("<title>Scrum of Scrums — Milestone Health</title>")
    h.append("""<style>
      body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif;
             max-width: 980px; margin: 24px auto; padding: 0 20px;
             background: #fafafa; color: #222; }
      h1 { margin: 0 0 4px 0; font-size: 24px; }
      .sub { color: #666; margin-bottom: 20px; font-size: 13px; }
      .rollup { background: #fff; padding: 14px 18px; border-radius: 10px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.05); margin-bottom: 20px;
                display: flex; gap: 20px; flex-wrap: wrap; font-size: 14px; }
      .rollup .pill { display: inline-flex; align-items: center; gap: 6px; }
      .dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
      h2 { margin: 28px 0 10px 0; padding-bottom: 6px; border-bottom: 1px solid #e0e0e0;
           font-size: 18px; }
      .card { background: #fff; padding: 14px 18px; border-radius: 10px;
              margin: 10px 0; box-shadow: 0 1px 3px rgba(0,0,0,0.05);
              border-left: 4px solid; }
      .card h3 { margin: 0 0 6px 0; font-size: 15px; display: flex;
                 align-items: center; gap: 8px; }
      .status-badge { font-size: 11px; padding: 2px 8px; border-radius: 10px;
                     background: #f3f4f6; color: #555; font-weight: 500; }
      .metrics { color: #555; font-size: 13px; margin: 4px 0; }
      .metrics b { color: #ef4444; }
      .impact { font-size: 13px; margin: 8px 0; color: #333; font-style: italic; }
      .signal { font-size: 12px; color: #f59e0b; font-weight: 500; }
      .tickets { margin-top: 8px; }
      .tickets a { font-size: 12px; color: #4f46e5; text-decoration: none; }
      .tickets a:hover { text-decoration: underline; }
      .ticket-row { font-size: 12px; color: #666; margin: 2px 0; padding-left: 8px;
                    border-left: 2px solid #e5e7eb; }
      .ticket-row .state { background: #eef; padding: 1px 6px; border-radius: 4px;
                          font-size: 10px; color: #4338ca; }
      .tsa-summary { font-size: 13px; color: #777; margin-left: 10px; font-weight: normal; }
    </style>""")
    h.append("</head><body>")
    h.append(f"<h1>Scrum of Scrums — Milestone Health</h1>")
    h.append(f"<div class='sub'>{health['date']} · source of truth: Linear · "
             f"<a href='https://linear.app/testbox'>open Linear →</a></div>")

    # rollup
    h.append("<div class='rollup'>")
    for s in ('red', 'yellow', 'green', 'done'):
        n = health['by_status'].get(s, 0)
        h.append(f"<span class='pill'><span class='dot' style='background:{status_colors[s]}'></span>"
                 f"<b>{n}</b> {STATUS_LABEL[s].lower()}</span>")
    h.append("</div>")

    for tsa in sorted(by_tsa.keys()):
        cards = by_tsa[tsa]
        counts = defaultdict(int)
        for c in cards:
            counts[c['status']] += 1
        summary = " · ".join(
            f"<span class='dot' style='background:{status_colors[s]}'></span>{counts[s]}"
            for s in ('red', 'yellow', 'green', 'done') if counts[s]
        )
        h.append(f"<h2>{html.escape(short_name(tsa))}"
                 f"<span class='tsa-summary'>  {summary}</span></h2>")
        for c in cards:
            m = c['metrics']
            color = status_colors[c['status']]
            header = html.escape(c['project'])
            if c['milestone']:
                header += f" — {html.escape(c['milestone'])}"
            h.append(f"<div class='card' style='border-left-color:{color}'>")
            h.append(f"<h3>{header} <span class='status-badge'>{STATUS_LABEL[c['status']]}</span></h3>")
            parts = [f"{m['open']} open / {m['total']} total"]
            if m['overdue']:
                parts.append(f"<b>{m['overdue']} overdue</b>")
            if m['soon'] and c['status'] != 'red':
                parts.append(f"{m['soon']} due ≤3d")
            if m['earliest_due']:
                parts.append(f"next due <code>{m['earliest_due']}</code>")
            h.append(f"<div class='metrics'>{' · '.join(parts)}</div>")
            h.append(f"<div class='impact'>Why it matters: {html.escape(c['impact'])}</div>")
            if c['status'] != 'green' and c['reasons']:
                h.append(f"<div class='signal'>Signal: {html.escape('; '.join(c['reasons']))}</div>")
            refs = [i for i in c.get('open_issues', []) if i.get('dueDate')]
            refs.sort(key=lambda x: x['dueDate'] or '9999-99-99')
            if refs:
                h.append("<div class='tickets'>")
                for issue in refs[:3]:
                    h.append(f"<div class='ticket-row'>"
                             f"<a href='{issue['url']}'>{issue['id']}</a> "
                             f"<span class='state'>{html.escape(issue['status'])}</span> "
                             f"{html.escape(issue['title'][:80])} "
                             f"<em>(due {issue['dueDate']})</em>"
                             f"</div>")
                h.append("</div>")
            h.append("</div>")

    h.append("<div class='sub' style='margin-top:24px'>Generated by TSA_CORTEX · "
             "<code>kpi/scrum_digest_builder.py</code></div>")
    h.append("</body></html>")
    return "\n".join(h)


def main():
    health = json.load(open(INPUT, encoding='utf-8'))

    md = render_markdown(health)
    slack = render_slack(health)
    html_out = render_html(health)

    with open(OUT_MD, 'w', encoding='utf-8') as f:
        f.write(md)
    with open(OUT_SLACK, 'w', encoding='utf-8') as f:
        f.write(slack)
    with open(OUT_HTML, 'w', encoding='utf-8') as f:
        f.write(html_out)

    print("Scrum Digest built:")
    print(f"  MD    : {OUT_MD}  ({len(md):,} chars)")
    print(f"  SLACK : {OUT_SLACK}  ({len(slack):,} chars)")
    print(f"  HTML  : {OUT_HTML}  ({len(html_out):,} chars)")


if __name__ == '__main__':
    main()
